### PR TITLE
fix Issue#106

### PR DESCRIPTION
**Pull request by KarlaChen**
Here is the issue I fixed.
Let me know if there is something you want me to change.

### CODE REVIEW

**Comment by raineorshine** [comment]
It looks like you may have added this commit to an existing branch. We want to add commits to master so we have a separate PR for each issue. You can try cherry-picking your commit into a new branch:

```sh
git checkout master
git checkout -b issue-106
git cherry-pick f3ea416
git push -u origin issue-106
```

**Comment by KarlaChen** [comment]
Ok, I will fix it.
Thank you.

**Comment by raineorshine** [comment]
Closing so we can start fresh. Make sure to use the issue title as the title, not the issue number.

**Comment by KarlaChen** [comment]
Got it, Thanks.

**Pull request closed without merging**
