### PR TITLE
Added shortcut to Home

### PR DESCRIPTION
**Pull request by esandez93**
Added a shortcut to Home page using ⌘ + ⇧ + H

### CODE REVIEW

**Comment by raineorshine** [comment]
Thank you!

You'll want to remove the `gesture` property. That is for mobile and would override the search gesture.

**Comment by esandez93** [comment]
Oh god, what a silly mistake! I'll fix right now, sorry!

**Comment by raineorshine** [comment]
Thanks!

**Comment by raineorshine** [comment]
@esandez93 Make sure to reference the related issue (#76). You can even write `Closes #76` in the commit and GitHub will automatically close the issue when the PR is merged!

**Pull request merged**
